apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.appName }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision }}
    path: {{ .Values.argocd.path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.argocd.destination.namespace }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
