apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-generator
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-generator
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-generator
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
subjects:
  - kind: ServiceAccount
    name: cert-generator
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: cert-generator
  apiGroup: rbac.authorization.k8s.io
