apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-patcher
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: day24-webhook-patcher
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "0"
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: day24-webhook-patcher
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "0"
subjects:
  - kind: ServiceAccount
    name: webhook-patcher
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: day24-webhook-patcher
  apiGroup: rbac.authorization.k8s.io
