apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: day24-approval-check
webhooks:
  - name: approval.day24.adventofkube.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: {{ .Values.namespace }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    clientConfig:
      service:
        name: admission-webhook
        namespace: {{ .Values.namespace }}
        path: /validate
      caBundle: {{ .Files.Get "ca.crt" | b64enc }}
