apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: {{ .Values.affinity.requiredLabel }}
                operator: In
                values:
                  - {{ .Values.affinity.requiredValue | quote }}
  containers:
    - name: {{ .Values.appName }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  restartPolicy: OnFailure
