apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  initContainers:
    - name: write-flag
      image: busybox:1.36
      command: ["sh", "-c", "echo 'FLAG_PLACEHOLDER' > /data/flag.txt"]
      volumeMounts:
        - name: data
          mountPath: /data
  containers:
    - name: {{ .Values.appName }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: day11-pvc
  restartPolicy: OnFailure
