apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-pipeline-config
  namespace: {{ .Values.namespace }}
data:
  promtail.yaml: |
    server:
      http_listen_port: 3101
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: pipeline-app
        static_configs:
          - targets:
              - localhost
            labels:
              job: pipeline-app
              __path__: /var/log/pods/*/*/*/*.log
        pipeline_stages:
          - regex:
              expression: '{{ .Values.promtail.pipeline.regex }}'
          - labels:
              level:
              message:
