apiVersion: v1
kind: ResourceQuota
metadata:
  name: day05-quota
  namespace: day05
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: "128Mi"
    limits.cpu: "400m"
    limits.memory: "256Mi"
