apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flag-cert
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.ingress.tlsSecret }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host }}
