namespace: day02
podName: day02-pod
image: busybox
flag: "AOK{c0nfigmap_c0nnected}"
configMapName: day02-config
# BUG: pod references this wrong name instead of configMapName
configMapRef: day02-settings
