namespace: day02
podName: day02-pod
image: busybox
flag: "AOK{crash_l00p_conquered}"
configMapName: day02-config
# BUG: pod references this wrong name instead of configMapName
configMapRef: day02-settings
